### PR TITLE
Improve and fix Help and About AssetViews

### LINKED ISSUE #550: Space between licenses is too big after update to 0.7
In the license overview there is too much space between the different licenses

screenshot_20160608-110733

### LINKED ISSUE #551: First Start Wizard - Progress Indicators too big after update to 0.7
during the first start wizard the progress indicator toggle boxes are too big:

screenshot_20160608-111238

### LINKED ISSUE #582: All items unter 'Help' let's crash the app
see images

help1 screenshot_2016-06-28-15-20-43

### LINKED ISSUE #588: Mixed german and english localization
Device with german language show a english message in alert dialog

Click at logout in settings

genlish

### PR DESCRIPTION
**Pull request by JoGir**
fixes #582 fixed nullpointer for activity in onCreate
fixes #550 fixed layout
fixes #588 added missing translations
fixes #551 added extra icon

### CODE REVIEW

File: qabelbox/src/main/java/de/qabel/qabelbox/fragments/AboutLicencesFragment.kt [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+        try {
+            activity.assets.open(filename).use {
+                stream ->
+                stream.bufferedReader().use {
+                    reader ->
+                    return reader.readText();
+                }
+            }
+        } catch (ex: IOException) {
+            throw RuntimeException("Could not read licencing info", ex)
```
Comment (audax) [inline qabelbox/src/main/java/de/qabel/qabelbox/fragments/AboutLicencesFragment.kt]: No need for that, Kotlin already does this.

File: qabelbox/src/main/java/de/qabel/qabelbox/fragments/AboutLicencesFragment.kt [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+import org.json.JSONObject
+import java.io.IOException
+
+class AboutLicencesFragment : BaseFragment() {
+
+    companion object {
+
+        internal val TAG = "AboutLicencesFragment"
+
+        fun newInstance(): AboutLicencesFragment {
```
Comment (audax) [inline qabelbox/src/main/java/de/qabel/qabelbox/fragments/AboutLicencesFragment.kt]: fun newInstance() = AboutLicencesFragment()

**Comment by audax** [comment]
Nothing really to complain here. :)

**Comment by audax** [comment]
No idea why the build server didn't check this but I kicked it off manually.
@julianseeger any idea?

**Comment by audax** [comment]
@JoGir please add a regression test for #582
