### PR TITLE
refresh quota on access

### LINKED ISSUE #720: Refresh box quota
* Update at startup
* Listen to box events

### LINKED ISSUE #725: Quota shown wrong in settings screen
After purchasing 10 GB option this has shown up in Brittas Client. Maybe even before but this is unconfirmed.
screenshot_20161004-104856

### PR DESCRIPTION
**Pull request by JoGir**
resolves #720
resolves #725
//TODO Check real server response matching format

### CODE REVIEW

File: qabelbox/src/main/java/de/qabel/qabelbox/account/AccountManager.java [hunk 1]
```diff
@@ -1,80 +0,0 @@
-package de.qabel.qabelbox.account;
```
Comment (enkore) [inline qabelbox/src/main/java/de/qabel/qabelbox/account/AccountManager.java]: From this diff it's hard to tell what the actual change is that fixed this.

Comment (JoGir) [inline qabelbox/src/main/java/de/qabel/qabelbox/account/AccountManager.java]: I just removed https://github.com/Qabel/qabel-android/pull/728/files#diff-82860000c643901cc1b744a460f92342L70 to refresh quota in background when calling getQuota. If the quota changed the manager sents an intent.

File: qabelbox/src/test/java/de/qabel/qabelbox/account/AccountManagerTest.java [hunk 2]
```diff
@@ -85,5 +87,32 @@ public Boolean call() throws Exception {
...
+            }
+        }, "Error waiting for changed quota");
+        assertEquals(AccountStatusCodes.QUOTA_UPDATED, statusCodes[0]);
+        quota = accountManager.getBoxQuota();
+
+        assertEquals(MockBlockServer.SIZE, quota.getSize());
+        assertEquals(MockBlockServer.QUOTA, quota.getQuota());
+
+        assertEquals(FileUtils.byteCountToDisplaySize(quota.getQuota()), "100 GB");
+        assertEquals(FileUtils.byteCountToDisplaySize(quota.getSize()), "1 KB");
```
Comment (julianseeger) [inline qabelbox/src/test/java/de/qabel/qabelbox/account/AccountManagerTest.java]: with some refactoring and removal of 90% of the testcode, this could look like
```JAVA
MockBlockServer.QUOTA = 100_GB;  // arrange
MockBlockServer.SIZE = 1_KB;

accountManager.getBoxQuota();  // act

waitForQuota("100 GB", "1 KB");  // assert
```

Thats what you need to test that the quota is fetched. If it's really important that the immediate return value of getBoxQuota is the old quota, then add a single assertion for that.
Arrange, Act, Assert ... easy to read, easy debug on failure and everything you should need. (Even though this wasn't written test driven, the second rule of tdd does still make sense).

With kotlin you could even clear that mysterious `waitForQuita and do`
```KOTLIN
MockBlockServer.QUOTA = 100_GB
MockBlockServer.SIZE = 1_KB

accountManager.getBoxQuota()

assertAsync(() -> { accountManager.boxQuota.quota }, equalTo(100_GB))
```

And you can pay the price of a second test method. Without the diff-highlighting, I wouldn't even read this test.

File: qabelbox/src/main/java/de/qabel/qabelbox/storage/model/BoxQuota.java [hunk 3]
```diff
@@ -21,4 +21,14 @@ public void setQuota(long quota) {
...
+    @Override
+    public boolean equals(Object o) {
+        if (o instanceof BoxQuota) {
+            BoxQuota other = (BoxQuota) o;
+            if (other.quota == this.quota && other.size == this.size) {
+                return true;
+            }
+        }
+        return false;
+    }
```
Comment (julianseeger) [inline qabelbox/src/main/java/de/qabel/qabelbox/storage/model/BoxQuota.java]: guard clause
```JAVA
public boolean equals(Object o) {
    if (!(o instanceof BoxQuota) {
        return false;
    }
    BoxQuota other = (BoxQuota)o;
    return other.quota == quota && other.size == size);
}
```

plain kotlin translation
```KOTLIN
fun equals(other: Object) {
    if (other !is Boxquota) {
        return false
    }
    return other.quota == quota && other.size == size
}
```

maximum shortness
```KOTLIN
fun equals(Object other) = other is BoxQuota && other.quota == qutota && other.size == size
```

I don't insist on a change of the structure but please remove the unneccessary `this` for the sake of collective code ownership.

**Comment by julianseeger** [comment]
Please remove all unneccessary usages of `this`. After that, feel free to merge
