### PR TITLE
Converted Settings Fragment and manually set ContactSync Preference

### LINKED ISSUE #712: Settings not match IndexPreferences
Android Preferences with direct binding to SharedPreferences not working for contact_sync in IndexPreferences.
SettingsFragment not shows correct contact_sync configuration.
Keep #710 in mind

### PR DESCRIPTION
**Pull request by JoGir**
resolves #712

### CODE REVIEW

File: qabelbox/src/main/java/de/qabel/qabelbox/settings/fragments/SettingsFragment.kt [hunk 1]
```diff
@@ -0,0 +1,136 @@
...
+import de.qabel.qabelbox.index.preferences.AndroidIndexPreferences
+import de.qabel.qabelbox.index.preferences.IndexPreferences
+import de.qabel.qabelbox.settings.SettingsActivity
+import de.qabel.qabelbox.settings.navigation.SettingsNavigator
+import de.qabel.qabelbox.storage.model.BoxQuota
+
+class SettingsFragment : PreferenceFragment() {
+
+    companion object {
+        val APP_PREF_NAME = AndroidIndexPreferences.KEY
```
Comment (julianseeger) [inline qabelbox/src/main/java/de/qabel/qabelbox/settings/fragments/SettingsFragment.kt]: `SettingsFragment.companion.getAPP_PREF_NAME` is maximum ugly ^^
There is an annotation that allows to drop the `.companion` and I think if you make APP_PREF_NAME a `const val ...`, you can access it as a field from Java. If not, please add a getter for the CrashReportingActivity or convert it to kotlin.

**Comment by JoGir** [comment]
There is a manual call to set checked value on the CheckBoxPreference for ContactSync

**Comment by JoGir** [comment]
We'll go to rewrite this fragment when adding more settings in groups for Chat, Abook, Box etc...
